version: '3'
services:
  app:
    image: xelastic-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./src:/src
      - ./docs:/docs
      - ./dist:/dist
      - ./howto:/howto
      - ./tests:/tests
      - ./setup.cfg:/setup.cfg
      - ./dev_readme.md:/dev_readme.py
      # - docker-logs:/logs
    ports:
      - 8000:8000 # used by mkdocs serve
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - 'path.repo=./backups'
    ports:
      - 9200:9200
    networks:
      - elastic

# volumes:
#   docker-logs: {}

networks:
  elastic:
